name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - debug

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Debug
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker image
        run: |
          # Get the current Git commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)

          # Define image name
          IMAGE_NAME="${{github.repository}}"

          docker build -t "${IMAGE_NAME}:latest" -t "${IMAGE_NAME}:${COMMIT_HASH}" .

      - name: Push Docker image
        run: |
          docker push ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:${COMMIT_HASH}